// 
// Copyright (c) 2011, Daniel Strother < http://danstrother.com/ >
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//   - Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//   - Redistributions in binary form must reproduce the above copyright
//     notice, this list of conditions and the following disclaimer in the
//     documentation and/or other materials provided with the distribution.
//   - The name of the author may not be used to endorse or promote products
//     derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
// EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
// TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

// auto-generated by dlsc_sortnet_generate.pl
// maximum inputs: 16

module dlsc_sortnet #(
    parameter INPUTS    = 1,        // 1 to 16
    parameter META      = 1,        // width of bypassed metadata
    parameter DATA      = 16,       // width of data for each element
    parameter ID        = 1,        // width of IDs for each element
    parameter PIPELINE  = 0,
    // derived; don't touch
    parameter ID_I      = (INPUTS*ID),
    parameter DATA_I    = (INPUTS*DATA)
) (
    input   wire                    clk,
    input   wire                    rst,

    input   wire                    in_valid,       // qualifier
    input   wire    [META-1:0]      in_meta,        // metadata to be delay-matched to sorting operation
    input   wire    [DATA_I-1:0]    in_data,        // unsorted data
    input   wire    [ID_I-1:0]      in_id,          // identifiers for unsorted data

    output  wire                    out_valid,      // delayed qualifier
    output  wire    [META-1:0]      out_meta,       // delayed in_meta
    output  wire    [DATA_I-1:0]    out_data,       // sorted data
    output  wire    [ID_I-1:0]      out_id          // identifiers for sorted data
);

`ifdef SIMULATION
initial begin
    if(INPUTS > 16) begin
        $display("[%m] *** ERROR *** INPUTS (%0d) exceeds generated maximum (16)",INPUTS);
    end
end
`endif

generate
    if(INPUTS == 1) begin:GEN_1
        assign out_valid    = in_valid;
        assign out_meta     = in_meta;
        assign out_data     = in_data;
        assign out_id       = in_id;
    end
    else if(INPUTS == 2) begin:GEN_2
        dlsc_sortnet_2 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_2_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 3) begin:GEN_3
        dlsc_sortnet_3 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_3_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 4) begin:GEN_4
        dlsc_sortnet_4 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_4_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 5) begin:GEN_5
        dlsc_sortnet_5 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_5_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 6) begin:GEN_6
        dlsc_sortnet_6 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_6_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 7) begin:GEN_7
        dlsc_sortnet_7 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_7_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 8) begin:GEN_8
        dlsc_sortnet_8 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_8_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 9) begin:GEN_9
        dlsc_sortnet_9 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_9_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 10) begin:GEN_10
        dlsc_sortnet_10 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_10_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 11) begin:GEN_11
        dlsc_sortnet_11 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_11_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 12) begin:GEN_12
        dlsc_sortnet_12 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_12_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 13) begin:GEN_13
        dlsc_sortnet_13 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_13_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 14) begin:GEN_14
        dlsc_sortnet_14 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_14_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 15) begin:GEN_15
        dlsc_sortnet_15 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_15_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else if(INPUTS == 16) begin:GEN_16
        dlsc_sortnet_16 #(
            .META       ( META ),
            .DATA       ( DATA ),
            .ID         ( ID ),
            .PIPELINE   ( PIPELINE )
        ) dlsc_sortnet_16_inst (
            .clk        ( clk ),
            .rst        ( rst ),
            .in_valid   ( in_valid ),
            .in_meta    ( in_meta ),
            .in_data    ( in_data ),
            .in_id      ( in_id ),
            .out_valid  ( out_valid ),
            .out_meta   ( out_meta ),
            .out_data   ( out_data ),
            .out_id     ( out_id )
        );
    end
    else begin:GEN_INVALID
        assign out_valid    = 1'bx;
        assign out_meta     = {META{1'bx}};
        assign out_data     = {DATA_I{1'bx}};
        assign out_id       = {ID_I{1'bx}};
    end
endgenerate

endmodule

